//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A19_Ex03_Alexey_332338060_Yevgeny_324759737.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("A19_Ex03_Alexey_332338060_Yevgeny_324759737.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afghanistan
        ///Albania
        ///Algeria
        ///Andorra
        ///Angola
        ///Antigua &amp; Deps
        ///Argentina
        ///Armenia
        ///Australia
        ///Austria
        ///Azerbaijan
        ///Bahamas
        ///Bahrain
        ///Bangladesh
        ///Barbados
        ///Belarus
        ///Belgium
        ///Belize
        ///Benin
        ///Bhutan
        ///Bolivia
        ///Bosnia Herzegovina
        ///Botswana
        ///Brazil
        ///Brunei
        ///Bulgaria
        ///Burkina
        ///Burundi
        ///Cambodia
        ///Cameroon
        ///Canada
        ///Cape Verde
        ///Central African Rep
        ///Chad
        ///Chile
        ///China
        ///Colombia
        ///Comoros
        ///Congo
        ///Congo {Democratic Rep}
        ///Costa Rica
        ///Croatia
        ///Cuba
        ///Cyprus
        ///Czech Republic
        ///Denmark
        ///Djibouti
        ///Dominica
        ///Dominican Republic
        ///E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DestinationCountries {
            get {
                return ResourceManager.GetString("DestinationCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap facebook_login {
            get {
                object obj = ResourceManager.GetObject("facebook_login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap facebook_logout_button {
            get {
                object obj = ResourceManager.GetObject("facebook_logout_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap left {
            get {
                object obj = ResourceManager.GetObject("left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Loading_icon {
            get {
                object obj = ResourceManager.GetObject("Loading_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afghanistan
        ///Albania
        ///Algeria
        ///Andorra
        ///Angola
        ///Antigua &amp; Deps
        ///Argentina
        ///Armenia
        ///Australia
        ///Austria
        ///Azerbaijan
        ///Bahamas
        ///Bahrain
        ///Bangladesh
        ///Barbados
        ///Belarus
        ///Belgium
        ///Belize
        ///Benin
        ///Bhutan
        ///Bolivia
        ///Bosnia Herzegovina
        ///Botswana
        ///Brazil
        ///Brunei
        ///Bulgaria
        ///Burkina
        ///Burundi
        ///Cambodia
        ///Cameroon
        ///Canada
        ///Cape Verde
        ///Central African Rep
        ///Chad
        ///Chile
        ///China
        ///Colombia
        ///Comoros
        ///Congo
        ///Congo {Democratic Rep}
        ///Costa Rica
        ///Croatia
        ///Cuba
        ///Cyprus
        ///Czech Republic
        ///Denmark
        ///Djibouti
        ///Dominica
        ///Dominican Republic
        ///E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OriginsCountries {
            get {
                return ResourceManager.GetString("OriginsCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap right {
            get {
                object obj = ResourceManager.GetObject("right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
